version: "3.3"

services:
  go-app:
    build: .
    environment:
      BMX_TOKEN: "${BMX_TOKEN}"
      CERT_FILE: "${CERT_FILE}"
      KEY_FILE: "${KEY_FILE}"
      PRIVATE_KEY: "${PRIVATE_KEY}"
      PUBLIC_KEY: "${PUBLIC_KEY}"
      PORT: 8000
      DSN_POSTGRESQL: "postgres://postgres:postgres@postgres:5432/bonds_db?sslmode=disable"
    ports:
      - 8000:8000
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: bonds_db
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./sql/*:/docker-entrypoint-initdb.d

volumes:
  postgres-data: {}
