package bootstrap

import (
	"database/sql"
	"net/http"

	bondLgc "github.com/erik-sostenes/bonds-publisher-challenge/internal/app/bonds/business/logic"
	bondPgrsql "github.com/erik-sostenes/bonds-publisher-challenge/internal/app/bonds/infrastructure/driven/postgresql"
	bondHlr "github.com/erik-sostenes/bonds-publisher-challenge/internal/app/bonds/infrastructure/drives/handlers"
	usrLgc "github.com/erik-sostenes/bonds-publisher-challenge/internal/app/users/business/logic"
	usrPgrsql "github.com/erik-sostenes/bonds-publisher-challenge/internal/app/users/infrastructure/driven/postgresql"
	usrHlr "github.com/erik-sostenes/bonds-publisher-challenge/internal/app/users/infrastructure/drives/handlers"
)

func BondInjector(db *sql.DB, mux *http.ServeMux) {
	bondSaver := bondPgrsql.NewBondSaver(db)
	bondCreator := bondLgc.NewBondCreator(bondSaver)

	bondOwnerUpdater := bondPgrsql.NewBondOwnerUpdater(db)
	bondBuyer := bondLgc.NewBondBuyer(bondOwnerUpdater)

	userBondsGetter := bondPgrsql.NewUserBondsGetter(db)
	userBondsRetriever := bondLgc.NewUserBondsRetriever(userBondsGetter)

	bondsGetter := bondPgrsql.NewBondsGetter(db)
	bondsRetriever := bondLgc.NewBondsRetriever(bondsGetter)

	newTokenValidator := usrLgc.NewTokenValidator(`LS0tLS1CRUdJTiBQVUJMSUMgS0VZLS0tLS0KTUlHZk1BMEdDU3FHU0liM0RRRUJBUVVBQTRHTkFEQ0JpUUtCZ1FESzBtV1JKeHAyNkxtd1dhajhIQU5kMjVhLwo4YzZjYXdFOHBXRk52SWhpVkwvWXpqc3dndXUxMUxjOEprQmV5S0xDdU5Kbmgya0I1di9SdlA4QldoWTdiMUU0CkkvMTRuMWUycUd2c0s1UFpLb2ZnWUMvN2tPckpUTFgrQ2R0WFFxS2p2SHVxWWdET1N5UmhMNWwvRElZdWFxdzcKY3Q0OE1OcVdzaFNKNi9PS1R3SURBUUFCCi0tLS0tRU5EIFBVQkxJQyBLRVktLS0tLQo=`)
	bondHlr.BondHandler(bondCreator, bondBuyer, userBondsRetriever, bondsRetriever, newTokenValidator, mux)
}

func UserInjector(db *sql.DB, mux *http.ServeMux) {
	usrSaver := usrPgrsql.NewUserSaver(db)
	usrCreator := usrLgc.NewUserCreator(usrSaver)

	privateKey := `LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JSUNkZ0lCQURBTkJna3Foa2lHOXcwQkFRRUZBQVNDQW1Bd2dnSmNBZ0VBQW9HQkFNclNaWkVuR25ib3ViQloKcVB3Y0ExM2Jsci94enB4ckFUeWxZVTI4aUdKVXY5ak9PekNDNjdYVXR6d21RRjdJb3NLNDBtZUhhUUhtLzlHOAovd0ZhRmp0dlVUZ2ovWGlmVjdhb2Erd3JrOWtxaCtCZ0wvdVE2c2xNdGY0SjIxZENvcU84ZTZwaUFNNUxKR0V2Cm1YOE1oaTVxckR0eTNqd3cycGF5Rklucjg0cFBBZ01CQUFFQ2dZQS9wemhwRGJTb2pQRjUveW1odGNqNHMrbmoKNDZmTVAyanI5NXRLSWxsTFF2M1N0U2F1V3VoTzhLdHhIVEFtanlGRnEydWRRa29hWnJ6eXZqWHAzclFLOCtPaQpSaGV3TWdqQmhXbTRwMkxSMW1nNnRWN1h4dXlFK2dlcW1BMU15VG9qQW1ZOGxxampQdEpiY0l3S1ZzU2hhNlNRCjc3Rkt5dnkxQzAvd3k4STVnUUpCQVBIM1NTeEN3OFMrd0diL25EbHNYc0M0ajlFViswRFRCSlVwSXZ0TFVqSVYKaUxqTXZqMXdFOVd5RDV4Sjlzamw2QXBHV2c2RjFoWXdyU20vWVFtTXpoa0NRUURXbGVZVms1aU4wTWNVeGtBQQpKcEVadW1RQlpCNVAxeGo1SEVnWGhvQU4rY2tjRUI0UkxpRFNrNHd2OGJNTGxHeG80dnhTc1h3bjZielRESjY3ClZOaW5Ba0JFTEhsSWFETkNYc0JWQk5YZWRBTXFaNVhWd2t5OVVmY3JrNkNRandORXF6NlBXdGlLOU9ZUndvNlYKYVYySDh3Ynl4aW1maCtQdThwNEhjaTJFQkZFWkFrRUFtWUEzUzkzK05neFFMVE00R3lON2pwei81dUxZc0NKZApjZTNpUURudHBwRzFaRWEvUzJqay85MmVYYm1YYThRcjNNZnEyYml1Nk5wU1FlTDROV2VYWndKQU9ZSWE2WUxYCi9mODRlUUc5QkROUjlGRGEvTW9LK210TXB0ZDZ5YW5LRkkrcS94U2hIRExsWmNwbkh1Tkt1UUlqRDlTU1prQUoKUG1va1VQZnhtemQ2MEE9PQotLS0tLUVORCBQUklWQVRFIEtFWS0tLS0tCg==`

	usrGetter := usrPgrsql.NewUserGetter(db)
	tokenGenerator := usrLgc.NewTokenGenerator(privateKey)
	usrAuthorizer := usrLgc.NewUserAuthorizer(tokenGenerator, usrGetter)

	usrHlr.UserHandler(usrCreator, usrAuthorizer, mux)
}
