name: golang

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Clone repository
      - name: Check out the repository
        uses: actions/checkout@v4

      # Configure the Go environment
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ">=1.22.0"
          check-latest: true
          cache: true

      # Install dependencies
      - name: Install dependencies
        run: go mod download
        working-directory: ./backend

      # Install golangci-lint
      - name: Install golangci-lint
        run: go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest

      # Execute linters
      - name: Run golangci-lint
        run: golangci-lint run --verbose
        working-directory: ./backend

      # Run tests
      - name: Test
        run: go test -v ./...
        working-directory: ./backend

      # Build app
      - name: Build
        run: go build -v ./...
        working-directory: ./backend
